name: Deploy my latest version

on:
  push: # What triggers a deployment. For example, `push`.
    branches:
      - main # What branch triggers a deployment. For example, `main`.

jobs:
  build:
    name: deploy from main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deployment
        uses: armory/cli-deploy-action@fix/workdir_CLOUD-882
        with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"  # "61ihoLa6dkk5SRwAy232H0TJk1xTBbK6"
          clientSecret:  "${{ secrets.CDAAS_CLIENT_SECRET }}" #Client secret that you created in the Armory Cloud Console that has been encrypted with GitHub's encrypted secrets.
          path-to-file: "/deploy-webhook.yml" # Path to the deployment file. For more information, see the Create a deployment file section.
          addContext: "demo-repo=peacemaker-webhooks-demo"
          applicationName: "cdf-th3morg-nginx"
